pantry = [
  "onions",
  "garlic",
  "apple cider vinegar",
  "olive oil",
  "butter",
  "bananas",
  "red beans",
  "lentils",
  "oatmeal",
  "white rice",
]
equipment = [
  "microwave",
  "electric burner",
  "instant pot",
  "rice cooker",
  "saucepan",
  "frying pan",
  "toaster",
]
